### ISSUE TITLE
Bug: Turning up volume toggles every module

### ISSUE THREAD

**Issue by BGP0** [ionar2/salhack#19] opened 2020-05-05 12:56 UTC
When I turn up my sound using my headphones (I have the Razer Kraken Kitty, there is a wheel on the back of it to turn up sound) Every module gets toggled. This causes my game to crash, and the only way to fix it is to delete salhack, or manually set all the "enabled" things in my modules folder to false. This is very annoying when I wait through the queue, then turn up my sound and get kicked instantly.

**Comment by dominikaaaa** [comment] 2020-05-05 13:11
Duplicate of #8, already fixed

**Closed by dominikaaaa** 2020-05-05 13:11 UTC
Labels: duplicate
