### ISSUE TITLE
Presets for auto crystal 

### ISSUE THREAD

**Issue by Bubba112** [ionar2/salhack#91] opened 2020-05-12 02:46 UTC
For when your pvping on different servers like 2b and 2bpvp are very different

**Comment by r-33** [comment] 2020-05-12 10:36
would these be premade presets made by ionar with different playstyles or different ca configs you make yourself and can swap on the fly?

**Comment by ionar2** [comment] 2020-05-12 11:52
Seems worse idea or duplicate of #50

**Comment by dominikaaaa** [comment] 2020-05-12 14:24
I don't understand why people can't make their own configurations and rely on others to make them. Just play the game for gods sake

**Closed** 2020-05-12 14:23 UTC
Labels: new/module
